Hw_6
pumulja/Fitnesss pull request #3
Opened 2018-03-28 11:00 UTC by pumulja

1. Подключить шрифты правильно
2. Сбросить стили по умолчанию - 
3. Сделать псевдоэлементы при наведении
4. Сделать футер
5. Выложить результат через НОВЫЙ Pull Request и отправить ссылку на Pull Request

2018-03-28 23:01 UTC, Afelua requested changes

2018-03-28 23:01 UTC, Afelua commented on style.css
> +@font-face{
Стоит указывать font-weight для каждого шрифта, который подключаете

2018-03-28 23:01 UTC, Afelua commented on style.css
> +font-weight: 300;
font-weight: 300 не будет работать до тех пор пока вы не зададите его в момент подключения самих шрифтов

2018-03-28 23:01 UTC, Afelua commented on style.css
> +@font-face{
И лучше название оставить только с типом шрифта, без указания начертания, т.е. AvenirNextCyr в данном случае. Аналогично для всех шрифтов

2018-03-29 17:49 UTC, pumulja commented on style.css
> +@font-face{
поправила!

2018-03-29 21:46 UTC, Afelua approved these changes

2018-03-30 05:51 UTC, merged