Hw_7final
pumulja/Fitnesss pull request #5
Opened 2018-03-31 11:12 UTC by pumulja

3. Проверить весь сайт по Pixel Perfect плагину.
4. Выложить через новый PR.

2018-04-01 19:56 UTC, Afelua requested changes

2018-04-01 19:56 UTC, Afelua commented on index.html
>          </nav>
Иконки внизу .social_button стоит поставить актуальные, из архива, кнопку .button тоже

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  min-width: 1600px;
Стоит убрать min-width: 1600px и поставить man-width: 1600px, иначе появляется горизонтальная прокрутка. Нам нужно, чтобы картинка не была больше, чем на макете, но меньше можно. Однако, стоит задать маленькое минимальное значение, при котором все блоки смотрятся корректно, например, 1200px.

Проверить по всем блокам, сделать так, чтобы гор прокрутка при экране до 1200px убралась.

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  left: 315px;
Здесь немного не совпадает
<img width="253" alt="screen shot 2018-04-01 at 22 42 38" src="https://user-images.githubusercontent.com/8777546/38176791-01532572-35fe-11e8-802d-30d12ff53e75.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  left: 210px;
Здесь стоит позиционировать не через left, а по центру всего блока, т.е. через margin: 0 auto;

И стоит задать максимальную ширину, при которой блок больше не тянется (согласно макету, чтобы подходило при наложении)

2018-04-01 19:56 UTC, Afelua commented on index.html
>              <img src="./images/icon1.svg">
Сделать так, чтобы эти картинки-иконки были заключены в отдельный тег и выравнить его высоту.  Нужно, чтобы все надписи под картинками стали располагаться на одном уровне по высоту. Было в конце одного из уроков.

2018-04-01 19:56 UTC, Afelua commented on style.css
> +.benefits-title {
Перепроверить margin
<img width="173" alt="screen shot 2018-04-01 at 22 46 50" src="https://user-images.githubusercontent.com/8777546/38176815-94c7bff2-35fe-11e8-9b09-017d4dd77d21.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  padding-bottom: 30px;
и padding тоже сделать актуальным
<img width="261" alt="screen shot 2018-04-01 at 22 47 24" src="https://user-images.githubusercontent.com/8777546/38176820-a95f0a7e-35fe-11e8-9746-f27f457f4b27.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +    margin: 0;
через margin задать отступ сверху 
<img width="1266" alt="screen shot 2018-04-01 at 22 48 12" src="https://user-images.githubusercontent.com/8777546/38176825-c65d932a-35fe-11e8-8887-fd62c52724d5.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  margin-top: 39px;
перепроверить отступы и размер текста. Для .title-h2 тоже 
<img width="310" alt="screen shot 2018-04-01 at 22 48 58" src="https://user-images.githubusercontent.com/8777546/38176829-e0979e0c-35fe-11e8-8bfa-bf87633fbd09.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  left: 265px;
отступы для блоков, которые всегда должны располагаться по центру, не принято делать через left. Для них нужно ограничивать width и задавать margin: 0 auto, как для benefits

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  left: 265px;
Соотвественно, posiition тоже не надо

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  margin-top: 75px;
Стили пишем только для классов, не для html-элементов. Перепроверить отступы. 
<img width="698" alt="screen shot 2018-04-01 at 22 51 58" src="https://user-images.githubusercontent.com/8777546/38176860-4c44d750-35ff-11e8-891d-53822e278e02.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +   padding: 10px;
Задать правильные padding и высоту
<img width="236" alt="screen shot 2018-04-01 at 22 52 36" src="https://user-images.githubusercontent.com/8777546/38176864-66283b26-35ff-11e8-9ab8-cc6b845f9664.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +   padding: 10px;
Аналогично для зеленой кнопки

2018-04-01 19:56 UTC, Afelua commented on style.css
> +   padding: 10px;
<img width="248" alt="screen shot 2018-04-01 at 22 53 09" src="https://user-images.githubusercontent.com/8777546/38176870-7776ad04-35ff-11e8-9fc0-5d83ddd41047.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  left: 265px;
Расположить form и .social_buttons на правильном расстоянии друг от друга. Для этого нужно поиграться с шириной footer-container

2018-04-01 19:56 UTC, Afelua commented on style.css
> +.social_buttons {
Задать правильную ширину элемента и убрать margin справа. Ширина - чтобы были равные отступы между иконками. 
<img width="360" alt="screen shot 2018-04-01 at 22 55 27" src="https://user-images.githubusercontent.com/8777546/38176892-c83e427e-35ff-11e8-9b1e-b9586c614fe6.png">

2018-04-01 19:56 UTC, Afelua commented on style.css
> +  height: 154px;
Задать актуальную высоту, чтобы не было белой полоски снизу 
<img width="163" alt="screen shot 2018-04-01 at 22 56 29" src="https://user-images.githubusercontent.com/8777546/38176900-ee1efb46-35ff-11e8-8abf-7abb1a8f1567.png">

2018-04-03 08:50 UTC, Afelua requested changes

2018-04-03 08:50 UTC, Afelua commented on index.html
> +          <li class="benefit-item">
Для них нужно прописать padding справа, чтобы было больше расстояние друг от друга
<img width="644" alt="screen shot 2018-04-03 at 11 12 21" src="https://user-images.githubusercontent.com/8777546/38237451-eb9b8ee4-372f-11e8-89cf-95d19ebd8130.png">

2018-04-03 08:50 UTC, Afelua commented on style.css
> +  background-image: url("https://image.flaticon.com/icons/svg/2/2738.svg");
Сделать все иконки картинками с макета (в папке images)

2018-04-03 08:50 UTC, Afelua commented on style.css
> +    right: 24px;
Задать правильный отступ справа для иконки
<img width="362" alt="screen shot 2018-04-03 at 11 48 14" src="https://user-images.githubusercontent.com/8777546/38239267-ebd88a74-3734-11e8-8f6a-2e54ba9e9cc4.png">

2018-04-03 08:50 UTC, Afelua commented on style.css
> +.content-link {
Задать правильный отступ padding сверху. Чтобы он сработал, присвоить display: inline-block;

<img width="193" alt="screen shot 2018-04-03 at 11 49 45" src="https://user-images.githubusercontent.com/8777546/38239354-2046d450-3735-11e8-85be-77e53117aad1.png">

2018-04-03 08:52 UTC, Afelua commented on style.css
> +.content-link {
Также убрать у .img-div-hover height: 100%, из-за этого часть формы внизу получается неактивной и ничего в ней нельзя написать.

2018-04-04 06:20 UTC, pumulja commented on index.html
> +          <li class="benefit-item">
поправила.

2018-04-04 06:20 UTC, pumulja commented on style.css
> +  background-image: url("https://image.flaticon.com/icons/svg/2/2738.svg");
поправила. но скачала с флетайкон все же, т к из папки выглядели некорректно вот так:

![2018-04-04 9 02 48](https://user-images.githubusercontent.com/37414367/38292110-2f42c11a-37eb-11e8-9749-c0bc71b0f337.png)

2018-04-04 06:37 UTC, pumulja commented on style.css
> +.content-link {
поправила и то и то

2018-04-04 06:54 UTC, pumulja commented on style.css
> +    right: 24px;
поправила

2018-04-04 07:47 UTC, Afelua approved these changes

2018-04-09 18:20 UTC, merged